services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=comments_db
    healthcheck:
          test: ["CMD", "curl", "-f", "http://app:3000/health-check"]
          interval: 5s
          timeout: 10s
          retries: 3

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: comments_db
    ports:
      - "3306:3306"
    volumes:
      - ./demo-project/starter-schema.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
          interval: 5s
          timeout: 10s
          retries: 3

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 5s
          timeout: 10s
          retries: 3

  test:
    build:
      context: .
      dockerfile: Dockerfile.e2etest
    depends_on:
      app:
        condition: service_healthy
    command: ["node", "e2e-tests/api.test.js"]

volumes:
  mysql-data:
