name: Workflow on Self-Hosted runner

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  helloworld:
    runs-on: ubuntu-shr

    steps:
      - run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files: "
          tree
